#!MC 1120
# Created by Tecplot 360 build 11.2-0-563
$!VarSet |MFBD| = '/home/liyq/bone2'
$!EXPORTSETUP EXPORTFORMAT = EPS
$!PRINTSETUP PALETTE = COLOR
$!EXPORTSETUP IMAGEWIDTH = 1275
$!EXPORTSETUP EPSPREVIEWIMAGE{IMAGETYPE = EPSIV2}
$!EXPORTSETUP EXPORTFNAME = '/home/liyq/bone2/export.eps'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
$!RemoveVar |MFBD|
